version: '3.7'

services:
  idempiere:
    image: idempiereofficial/idempiere:10
    volumes:
      - idempiere_config:/opt/idempiere/configuration
      - idempiere_plugins:/opt/idempiere/plugins
    environment:
      - TZ=GMT
    ports:
      - 8080:8080
      - 8443:8443
      - 12612:12612

  postgres:
    image: postgres:13
    volumes:
      - idempiere_data:/var/lib/postgresql/data
    environment:
      - TZ=GMT
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  idempiere_data:
  idempiere_plugins:
  idempiere_config: